### ISSUE TITLE
Code Crashes

### ISSUE THREAD

**Issue by GangYLu** [htwangtw/nbackexpsampling#3]
Hello, I have a problem of running the code. It crashed after a couple of non-target trials presented, besides I couldn't use the keyboard to skip the instruction but the key "Enter" worked. The output showed "Experiment ended with exit code 1 [pid:11916]".

**Comment by htwangtw** [comment]
Sorry I don't have the capacity to maintain this code base any more. 
If you managed to fix it, I am happy to review the fix.
However, I won't push any new changes.

**Comment by GangYLu** [comment]
Ok, thanks for your response.
